export const TARGET_WORDS = [
  'APPLE', 'BEACH', 'CRANE', 'DANCE', 'EARTH',
  'FLAME', 'GRAPE', 'HOUSE', 'IVORY', 'JOINT',
  'KNIFE', 'LEMON', 'MUSIC', 'NORTH', 'OCEAN',
  'PLANT', 'QUEEN', 'RIVER', 'STONE', 'TRAIN'
];

export const VALID_WORDS = new Set([
  ...TARGET_WORDS,
  'AISLE', 'ALERT', 'ANGER', 'AWARE', 'BADLY',
  'BASIC', 'BEATS', 'BLIND', 'BLOCK', 'BOOST',
  'BOOTH', 'BRAIN', 'BRAND', 'BREAD', 'BREAK',
  'BREED', 'BRIEF', 'BRING', 'BROAD', 'BROKE',
  'BROWN', 'BUILD', 'BUILT', 'CABLE', 'CARRY',
  'CATCH', 'CAUSE', 'CHAIN', 'CHAIR', 'CHART',
  'CHASE', 'CHEAP', 'CHECK', 'CHEST', 'CHIEF',
  'CHILD', 'CHINA', 'CHOSE', 'CIVIL', 'CLAIM',
  'CLASS', 'CLEAN', 'CLEAR', 'CLICK', 'CLOCK',
  'CLOSE', 'CLOUD', 'COACH', 'COAST', 'COULD',
  'COUNT', 'COURT', 'COVER', 'CRAFT', 'CRASH',
  'CRAZY', 'CROSS', 'CROWD', 'CROWN', 'CRUDE',
  'CURVE', 'CYCLE', 'DAILY', 'DATED', 'DEALT',
  'DEATH', 'DEBUT', 'DELAY', 'DEPTH', 'DOING',
  'DOUBT', 'DOZEN', 'DRAFT', 'DREAM', 'DRESS',
  'DRILL', 'DRINK', 'DRIVE', 'DROVE', 'DYING'
]);